# Change these first
owner: hinzwifi # Your GitHub organization or username, where this repository lives
repo: uptime-hinz # The name of this repository

sites:
  - name: Main Page
    url: https://hinzwifi.xyz
  - name: Î¼logger
    url: https://gps.hinzwifi.xyz/
  - name: Pastebin
    url: https://paste.hinzwifi.xyz/
  - name: Plainpad
    url: https://notes.hinzwifi.xyz/public/
  - name: File Share
    url: https://share.hinzwifi.xyz/
  - name: KeeWeb
    url: https://hinzwifi.xyz/passwords/
  - name: MyIIT
    url: http://x4150my.msuiit.edu.ph/my/getmyiit.php
  - name: Birthdays
    url: https://m.hinzwifi.xyz
  

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: up.hinzwifi.xyz
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: UpHinz
  introTitle: "Welcome to hinz's status monitor page"
  introMessage: I check my websites here.
  theme: dark
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  robotsText: "User-agent: * \n Disallow: /"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
